---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO,,}
    username: jones2026

- name: docker_pushrm
  image: chko/docker-pushrm
  environment:
    DOCKER_USER: jones2026
    DOCKER_PASS:
      from_secret: docker_password
    PUSHRM_TARGET: docker.io/jones2026/nginx-artifactory-cache
    PUSHRM_DEBUG: 1
    PUSHRM_FILE: README.md

trigger:
  branch:
  - main

...